/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simple.crud;

import com.mysql.cj.xdevapi.Table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Jon Ken Vergara
 */
public class Createc extends javax.swing.JFrame {
 private DefaultTableModel model;
 private javax.swing.JTable Table;
 private ViewC parentView;
    /**
     * Creates new form Create
     */
    public Createc(DefaultTableModel model, ViewC parentView) {
    initComponents();
    this.model = model;
    this.parentView = parentView;
}
    
    public Createc() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/simple/crud/logoh&h.jpeg"));  
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pNum1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CUSTOMER'S INFORMATION");
        setMinimumSize(new java.awt.Dimension(598, 481));
        getContentPane().setLayout(null);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(130, 236, 338, 39);

        jLabel4.setBackground(new java.awt.Color(61, 52, 21));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 214, 40, 16);

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        getContentPane().add(fName);
        fName.setBounds(130, 102, 338, 39);

        jLabel2.setBackground(new java.awt.Color(61, 52, 21));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 80, 60, 20);

        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        getContentPane().add(lName);
        lName.setBounds(130, 169, 338, 39);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 147, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phone Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 281, 90, 16);

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Address);
        Address.setBounds(130, 370, 338, 37);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 350, 50, 16);

        pNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNum1ActionPerformed(evt);
            }
        });
        getContentPane().add(pNum1);
        pNum1.setBounds(130, 303, 338, 37);

        jLabel6.setBackground(new java.awt.Color(61, 52, 21));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer's Information");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 20, 430, 50);

        submit.setBackground(new java.awt.Color(61, 52, 21));
        submit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(480, 370, 90, 39);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simple/crud/bg create.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-33, -14, 640, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void pNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNum1ActionPerformed
  public void updateParentTable() {
    if (parentView != null) {
        parentView.loadData();
    }
}

    
    public void loadData(){
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:MySQL://localhost:3306/java_users_db";
        String user = "root";
        String pass = "";

        Connection con = DriverManager.getConnection(url, user, pass);
        Statement st = con.createStatement();
            
       DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "First Name", "Last Name", "Email", "Phone Number", "Address"}, 0);
        model.setRowCount(0);
       Table.setModel(model);
       String sql = "SELECT * FROM user";
       
       ResultSet rs = st.executeQuery(sql);
       String i, f, l,e, p, a;
       while(rs.next()){
         i = rs.getString("id");
         f = rs.getString("first_name");
         l = rs.getString("last_name");
         e = rs.getString("email");
         p = rs.getString("phone");
         a = rs.getString("address");
         model.addRow(new Object[]{i, f, l, e, p, a});
       }
     }catch(Exception e){
            System.out.println("Error "+ e.getMessage());
     }   
                
       
    }
  private void submitActionPerformed(java.awt.event.ActionEvent evt) {                                       
    String fN, lN, em, pm, ad, query;

    //connect to database
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:MySQL://localhost:3306/java_users_db";
        String user = "root";
        String pass = "";

        Connection con = DriverManager.getConnection(url, user, pass);
        Statement st = con.createStatement();

        if ("".equals(fName.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "First Name is required", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(lName.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Last Name is required", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(email.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Email Address is required", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(pNum1.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Phone Number is required", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(Address.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Address is required", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            fN = fName.getText();
            lN = lName.getText();
            em = email.getText();
            pm = pNum1.getText();
            ad = Address.getText();
            query = "INSERT INTO user (first_name, last_name, email, phone, address) "
                    + "VALUES ('" + fN + "','" + lN + "','" + em + "','" + pm + "','" + ad + "')";

            // Execute the insertion query and retrieve the generated keys
            st.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            ResultSet generatedKeys = st.getGeneratedKeys();

            if (generatedKeys.next()) {
                int generatedID = generatedKeys.getInt(1); // Assuming the ID is an integer
                JOptionPane.showMessageDialog(null, "Successfully registered. Generated ID: " + generatedID);

                Object[] newRow = {generatedID, fN, lN, em, pm, ad};
                model.addRow(newRow);
                loadData();
                con.close();
                updateParentTable();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error retrieving generated ID");
            }
        }
    } catch (Exception e) {
        System.out.println("Error " + e.getMessage());
    }
}
  private int getNextID() {
    int rowCount = model.getRowCount();
    if (rowCount == 0) {
        return 1; // If there are no rows, start from 1
    } else {
        // Find the maximum ID value in the existing rows and increment by 1
        int maxID = Integer.parseInt(model.getValueAt(rowCount - 1, 0).toString());
        return maxID + 1;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Createc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField pNum1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
