/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simple.crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jon Ken Vergara
 */
public class UpdateE extends javax.swing.JFrame {
     private DefaultTableModel model;
     private View parentView;
    /**
     * Creates new form UpdateE
     * @param model
     * @param parentView
     */
    public UpdateE(DefaultTableModel model, View parentView) {
        initComponents();
        this.model = model;
        this.parentView = parentView;
        ImageIcon icon = new ImageIcon(getClass().getResource("/simple/crud/logoh&h.jpeg"));  
        setIconImage(icon.getImage());
        
        // Set the minimum selectable date for jDateChooser1 to the current date
        jDateChooser1.setDate(new Date()); 
        jDateChooser1.setMinSelectableDate(new Date());
        
        // Set the minimum selectable date for jDateChooser2 to the current date
        jDateChooser2.setDate(new Date());
        jDateChooser2.setMinSelectableDate(new Date());
    
    
    }
    
     public void loadData() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:MySQL://localhost:3306/java_users_db";
        String user = "root";
        String pass = "";

        Connection con = DriverManager.getConnection(url, user, pass);
        Statement st = con.createStatement();

        DefaultTableModel model = new DefaultTableModel(new String[]{"OrderId", "customerId", "eplace", "orderdate", "eventdate", "total", "status"}, 0);
        model.setRowCount(0);  // Clear existing rows
        parentView.setTableModel(model);  // Update the table in the parent view

        String sql = "SELECT * FROM event";

        ResultSet rs = st.executeQuery(sql);
        String o, c, e, r, v, t, s;
        while (rs.next()) {
            o = rs.getString("OrderId");
            c = rs.getString("customerId");
            e = rs.getString("eplace");
            r = rs.getString("orderdate");
            v = rs.getString("eventdate");
            t = rs.getString("total");
            s = rs.getString("status");
            model.addRow(new Object[]{o, c, e, r, v, t, s});
        }

        con.close();
    } catch (Exception e) {
        System.out.println("Error " + e.getMessage());
    }
}

     private String getSelectedButtonText(ButtonGroup buttonGroup) {
    for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
        AbstractButton button = buttons.nextElement();
        if (button.isSelected()) {
            return button.getText();
        }
    }
    return null; // Return null or handle the case when no button is selected
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusgroup = new javax.swing.ButtonGroup();
        serachData = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        searchBtn1 = new javax.swing.JButton();
        Clear1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ePlace = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 550));
        getContentPane().setLayout(null);

        serachData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachDataActionPerformed(evt);
            }
        });
        getContentPane().add(serachData);
        serachData.setBounds(130, 420, 252, 39);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search By ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 400, 80, 16);

        searchBtn1.setBackground(new java.awt.Color(61, 52, 21));
        searchBtn1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("Find");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn1);
        searchBtn1.setBounds(390, 420, 72, 37);

        Clear1.setBackground(new java.awt.Color(61, 52, 21));
        Clear1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        Clear1.setForeground(new java.awt.Color(255, 255, 255));
        Clear1.setText("Clear");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });
        getContentPane().add(Clear1);
        Clear1.setBounds(470, 420, 72, 37);

        update1.setBackground(new java.awt.Color(61, 52, 21));
        update1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setText("UPDATE");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        getContentPane().add(update1);
        update1.setBounds(480, 370, 90, 39);

        delete1.setBackground(new java.awt.Color(61, 52, 21));
        delete1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete1);
        delete1.setBounds(480, 317, 90, 40);

        jLabel6.setBackground(new java.awt.Color(61, 52, 21));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EVENTS UPDATER");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 20, 320, 50);

        jLabel2.setBackground(new java.awt.Color(61, 52, 21));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Place");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 80, 70, 20);

        ePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePlaceActionPerformed(evt);
            }
        });
        getContentPane().add(ePlace);
        ePlace.setBounds(130, 102, 338, 39);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 147, 70, 20);

        jLabel4.setBackground(new java.awt.Color(61, 52, 21));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 214, 70, 16);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Amount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 281, 80, 16);

        totalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAActionPerformed(evt);
            }
        });
        getContentPane().add(totalA);
        totalA.setBounds(130, 303, 338, 37);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 350, 50, 16);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(130, 170, 338, 39);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(130, 240, 338, 39);

        statusgroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jRadioButton1.setText("Pending");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(80, 370, 98, 21);

        statusgroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jRadioButton2.setText("Confirmed");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(180, 370, 98, 21);

        statusgroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jRadioButton3.setText("Completed");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(280, 370, 98, 21);

        statusgroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jRadioButton4.setText("Canceled");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(380, 370, 98, 21);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simple/crud/upe.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-830, -170, 1490, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePlaceActionPerformed

    private void totalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void serachDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serachDataActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        String ID;
        int notFound = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:MySQL://localhost:3306/java_users_db";
            String user = "root";
            String pass = "";

            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            ID = serachData.getText();
            if("".equals(ID)){
                JOptionPane.showMessageDialog(new JFrame(), "ID is require", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
            }else {
                String sql = "SELECT * FROM event WHERE orderId="+ID;
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    ePlace.setText(rs.getString("eplace"));
                    java.sql.Date orderDate = rs.getDate("orderdate");
                    jDateChooser1.setDate(orderDate);
                    java.sql.Date eventDate = rs.getDate("eventdate");
                    jDateChooser2.setDate(eventDate);
                    totalA.setText(rs.getString("total"));
                    String status = rs.getString("status");

// Iterate through the radio buttons in the button group
                    Enumeration<AbstractButton> buttons = statusgroup.getElements();
                    while (buttons.hasMoreElements()) {
    AbstractButton button = buttons.nextElement();

    // Check if the button's text matches the retrieved status
    if (button.getText().equals(status)) {
        // Set this button as selected
        button.setSelected(true);
    }
}
                    notFound = 1;

                    con.close();
                }
                if(notFound == 0){
                    JOptionPane.showMessageDialog(new JFrame(), "invalid ID", "Dialog",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            System.out.println("Error "+ e.getMessage());

        }
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
        ePlace.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        totalA.setText("");
        statusgroup.clearSelection();
    }//GEN-LAST:event_Clear1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String ID;
int notFound = 0;
String ep, ta, sg;
Date od, ed; // Corrected variable names
try {
    Class.forName("com.mysql.cj.jdbc.Driver");

    String url = "jdbc:MySQL://localhost:3306/java_users_db";
    String user = "root";
    String pass = "";

    Connection con = DriverManager.getConnection(url, user, pass);
    Statement st = con.createStatement();

    ID = serachData.getText();
    if ("".equals(ID)) {
        JOptionPane.showMessageDialog(new JFrame(), "ID is required", "Dialog",
                JOptionPane.ERROR_MESSAGE);
    } else {
        String sql = "SELECT * FROM event WHERE orderId=" + ID;
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            notFound = 1;
            ep = ePlace.getText();
            od = jDateChooser1.getDate(); 
            ed = jDateChooser2.getDate(); 
            ta = totalA.getText();
            sg = getSelectedButtonText(statusgroup);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            // Format dates to strings
            String orderDateStr = (od != null) ? dateFormat.format(od) : "";
            String eventDateStr = (ed != null) ? dateFormat.format(ed) : "";

            String sql2 = "UPDATE event SET eplace='" + ep + "', orderdate='" + orderDateStr + "', eventdate='" + eventDateStr + "', total='" + ta + "', status='" + sg + "' WHERE orderId=" + ID;
            st.executeUpdate(sql2);
            loadData();
            con.close();
        }
        if (notFound == 0) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid ID", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
} catch (Exception e) {
    System.out.println("Error " + e.getMessage());
}
    }//GEN-LAST:event_update1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        String ID;
        int notFound = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:MySQL://localhost:3306/java_users_db";
            String user = "root";
            String pass = "";

            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            ID = serachData.getText();
            if("".equals(ID)){
                JOptionPane.showMessageDialog(new JFrame(), "ID is require", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
            }else {
                String sql = "SELECT * FROM event WHERE orderId="+ID;
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    notFound = 1;
                    String sql2 = "DELETE FROM event WHERE orderId="+ID;
                    st.executeUpdate(sql2);
                    loadData();
                    con.close();
                }
                if(notFound == 0){
                    JOptionPane.showMessageDialog(new JFrame(), "invalid ID", "Dialog",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            System.out.println("Error "+ e.getMessage());

        }
    }//GEN-LAST:event_delete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DefaultTableModel model = new DefaultTableModel();
                View parentView = new View();  
                new UpdateE(model, parentView).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear1;
    private javax.swing.JButton delete1;
    private javax.swing.JTextField ePlace;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField serachData;
    private javax.swing.ButtonGroup statusgroup;
    private javax.swing.JTextField totalA;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
