/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simple.crud;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;









/**
 *
 * @author Rahemet
 */
public class ViewC extends javax.swing.JFrame {

 
    
   public javax.swing.JTable getTable() {
        return Table;
    }
   public void setTableModel(DefaultTableModel model) {
        Table.setModel(model);
    }
    public ViewC() {
        initComponents();
        addButtonListeners();
         loadData();
    }
    
     private void addButtonListeners() {
        // ... (your existing button listeners)

        // Add an action listener to the "Create" button
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                openCreateFrame();
            }
        });
    }
  
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JAVA CRUD GUI Application"); // NOI18N
        setMinimumSize(new java.awt.Dimension(1240, 1240));
        setPreferredSize(new java.awt.Dimension(1240, 1240));
        getContentPane().setLayout(null);

        submit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        submit.setText("Create");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(102, 87, 100, 50);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setPreferredSize(new java.awt.Dimension(500, 400));
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 160, 830, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simple/crud/bgview.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(12412312, 1241231));
        jLabel1.setMinimumSize(new java.awt.Dimension(1242, 1240));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1480, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
   private void openCreateFrame() {
        Createc createFrame = new Createc((DefaultTableModel) Table.getModel(),this);
        createFrame.setLocationRelativeTo(this);
        createFrame.setVisible(true);
        
    }
    public void loadData(){
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:MySQL://localhost:3306/java_users_db";
        String user = "root";
        String pass = "";

        Connection con = DriverManager.getConnection(url, user, pass);
        Statement st = con.createStatement();
            
       DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
      
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);

        for (int i = 0; i < model.getColumnCount(); i++) {
            Table.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }
       Table.setModel(model);
       String sql = "SELECT * FROM user";
       
       ResultSet rs = st.executeQuery(sql);
       String i, f, l, e, p, a ;
       while(rs.next()){
         i = rs.getString("id");
         f = rs.getString("first_name");
         l = rs.getString("last_name");
         e = rs.getString("email");
         p = rs.getString("phone");
         a = rs.getString("address");
         model.addRow(new Object[]{i, f, l, e, p, a});
       }
       Table.setModel(model);

     }catch(Exception e){
            System.out.println("Error "+ e.getMessage());
     }   
                
       
    }
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        openCreateFrame();
        
        //        String fN, lN, em, query;
//        
//        
//        //connect to database
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            
//            String url = "jdbc:MySQL://localhost:3306/java_users_db";
//            String user = "root";
//            String pass = "";
//            
//            Connection con = DriverManager.getConnection(url, user, pass);
//            Statement st = con.createStatement();
//            
//            if("".equals(fName.getText())){
//             
//                JOptionPane.showMessageDialog(new JFrame(), "First Name is require", "Dialog",
//                                     JOptionPane.ERROR_MESSAGE);
//            }else if("".equals(lName.getText())){
//             
//                JOptionPane.showMessageDialog(new JFrame(), "Last Name is require", "Dialog",
//                                     JOptionPane.ERROR_MESSAGE);
//            }else if("".equals(email.getText())){
//             
//                JOptionPane.showMessageDialog(new JFrame(), "Email Adress is require", "Dialog",
//                                     JOptionPane.ERROR_MESSAGE);
//            }else {
//                fN = fName.getText();
//                lN = lName.getText();
//                em = email.getText();
//                query = "INSERT INTO user (first_name, last_name, email) "
//                        + "VALUES ('"+fN+"','"+lN+"','"+em+"')";
//               
//               st.executeUpdate(query);
//               fName.setText("");
//               lName.setText("");
//               email.setText("");
//               showMessageDialog(null, "Successfully registered.");
//               loadData();
//               con.close();
//            }   
//        }catch(Exception e){
//            System.out.println("Error "+ e.getMessage());
//            
//        }
//        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//       
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//                View x = new View();
//                x.loadData();
//                x.setLocationRelativeTo(null);
//                x.setVisible(true);
//                
//                new Create().loadData();
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
  
}

